### ISSUE TITLE
centos 7.3 and ftpfs

### ISSUE THREAD

**Issue by zambanini** [rr-/ftpfs#1]
> # pip install ftpfs --user
> Requirement already satisfied: ftpfs in /root/.local/lib/python2.7/site-packages (0.2)
> Requirement already satisfied: fusepy in /root/.local/lib/python2.7/site-packages (from ftpfs) (3.0.1)

> [borg@localhost ~]$ pip install ftpfs --user
> Collecting ftpfs
>   Downloading https://files.pythonhosted.org/packages/1e/ab/c5a33b7ccb49ed4facac513ad7942224b1ac1a0f617e49f35d0ba6e70858/ftpfs-0.2.tar.gz
> Collecting fusepy (from ftpfs)
>   Downloading https://files.pythonhosted.org/packages/04/0b/4506cb2e831cea4b0214d3625430e921faaa05a7fb520458c75a2dbd2152/fusepy-3.0.1.tar.gz
> Installing collected packages: fusepy, ftpfs
>   Running setup.py install for fusepy ... done
>   Running setup.py install for ftpfs ... done
> Successfully installed ftpfs-0.2 fusepy-3.0.1
> [borg@localhost ~]$ ftpfs
> Traceback (most recent call last):
>   File "/home/borg/.local/bin/ftpfs", line 9, in <module>
>     load_entry_point('ftpfs==0.2', 'console_scripts', 'ftpfs')()
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
>     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
>   File "/home/borg/.local/lib/python2.7/site-packages/ftpfs/__main__.py", line 19
>     print(*args)
>           ^
> SyntaxError: invalid syntax

ftpfs 172.18.51.17 /mnt/calmotion does the same.

do you have any hint?

**Comment by rr-** [comment]
You're using Python 2.7, whereas the minimum supported Python version is 3.x (I don't remember which version exactly).

**Comment by zambanini** [comment]
>  [borg@localhost __pycache__]$ ftpfs 172.18.51.17 /mnt/calmotion1
> Traceback (most recent call last):
>   File "/home/borg/.local/bin/ftpfs", line 9, in <module>
>     load_entry_point('ftpfs==0.2', 'console_scripts', 'ftpfs')()
>   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2379, in load
>     return self.resolve()
>   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2385, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/borg/.local/lib/python3.4/site-packages/ftpfs/__main__.py", line 126
>     self._ftp.sendcmd(f'SITE CHMOD {mode & 0o777:3o} {path}')
>                                                            ^
> 

is there any debug switch, to see what args the script sees? or do you offer paid remote support (no rush)

**Comment by rr-** [comment]
The error message is about Python being unable to parse f-strings, which were introduced in Python 3.6 (so turns out the project requires Python 3.6 to run).
I can backport the package to 3.4 if you want :)
